### PR TITLE
Feature: Tool Enhancements

### LINKED ISSUE #18: Add alternatives to tools
For example, say that a tool (git-hooks) uses Git 2.9.0 and the user does not want to change their Git version. The Starterfile may look like:

```

tools:
  git-hooks:
    alt: git-hooks-py
    scripts:
      check: git --version # | semver xxx
      install: git config ...
      destroy: git config ...
  git-hooks-py:
    check: python --version
    install: python ./scripts/install-git-hooks.py

```

Allowing for fallback version of tools

### LINKED ISSUE #20: Don't uninstall Tools on fail if previously installed
A tool failing could uninstall an existing user's tool, bad

### PR DESCRIPTION
**Pull request by trentonyo**
Tool Enhancements
===========

> **ASSOCIATED ISSUES:**
>
> 
> 
> 
>
> 
> 
> 
> - Closes #18 
> - Closes #20

Description
-----------

🧰🤔 **Tool Installation Modes:** Tools were given more granular control over how they are installed: 

- `alt`: Allows Path designers to specify a "backup" choice for when a Tool fails to install for any reason.
- `mode`:
  - `install` (Default): Tool is installed as usual
  - `optional`: User is prompted y/N to install the Tool
  - `as_alt`: Tool is only installed if it is specified as an alt for a tool that fails to install

🧱🏠 **Don't Uninstall Me, bro!** Tools which were already installed will not be uninstalled during the rollback step of Tool installation.

Definition of Done
------------------

* [x] Changes are approved
* [x] Contains no breaking changes
* [x] Changes are implemented in all components
* [x] Each component associated with issue is updated (no stubs)
* [x] Each new feature has unit tests written and confirmed
* [x] All tests pass, no regressions
* [x] All documentation is updated, including release notes

### CODE REVIEW

**Comment by trentonyo** [comment]
I know I've said this before, but I think that you should really be able to use:

<details>

<summary>Linux/MacOS</summary>

```shell
cd /tmp
python -m venv .venv
source .venv/bin/activate
pip install typer schema pyyaml requests python-dotenv rich parameterized pytest pytest-cov
pip install -i https://test.pypi.org/simple/ startout==0.4.3
```

</details>


<details>

<summary>Windows</summary>

```shell
cd /tmp
python -m venv .venv 
.venv/Scripts/activate
pip install typer schema pyyaml requests python-dotenv rich parameterized pytest pytest-cov
pip install -i https://test.pypi.org/simple/ startout==0.4.3
```

</details>

to test this version, it is available on Python 3.8-3.12

**Review by Gehrkej — COMMENTED** [review]
When running the commands in the previous comment I was met with this output. 
image

**Comment by Gehrkej** [comment]
> When running the commands in the previous comment I was met with this output. image

Here is the version of Python I have installed: 
image

I am testing on windows 10 btw.

**Comment by trentonyo** [comment]
That's interesting, I'll look into it

**Pull request merged**
