### PR TITLE
FEATURE: Starterfile Enhancements

### LINKED ISSUE #15: Add command for just parsing and running Starterfile
Something like `startout-starter up`

This will support local testing, development, and recovering from errors

This also paves the way for future features like
- `startout-starter start`
- `startout-starter uninstall`
- `startout-starter update`

### LINKED ISSUE #16: Do env replacement on Startersteps.md
This files gives explicit instructions for the manual configuration steps that need to be carried out, and includes links that will need data from the `up` run

### PR DESCRIPTION
**Pull request by trentonyo**
Starterfile Enhancements
===========

> **ASSOCIATED ISSUES:**
>
> 
> 
> 
>
> 
> 
> 
> - Closes #16 
> - Closes #15 

Description
-----------

🚀 **Starterfile run utility:** Added command for just running a Starterfile without cloning a repo (as in the case of designing/testing a Path, or recovering from an error). (Use `startout-starter`)

📝 **Env replacement in Startersteps:** `Starterfile.up()` now replaces environment variables in the Startersteps.md instructions, in preparation for steps that must be carried out manually.

Definition of Done
------------------

* [x] Changes are approved
* [x] Contains no breaking changes
* [x] Changes are implemented in all components
* [x] Each component associated with issue is updated (no stubs)
* [x] Each new feature has unit tests written and confirmed
* [x] All tests pass, no regressions
* [x] All documentation is updated, including release notes

### CODE REVIEW

**Comment by trentonyo** [comment]
For testing purposes, try installing from the test index with

```
python -m pip install -i https://test.pypi.org/simple/ startout==0.2.2
```

**Comment by HlaKarki** [comment]
> For testing purposes, try installing from the test index with
> 
> ```
> python -m pip install -i https://test.pypi.org/simple/ startout==0.2.2
> ```

Is there any preliminary stuff I might have needed to do before running that command? As of now, this is what I see. I used macOS.
Screenshot 2024-08-06 at 7 03 54 PM

**Comment by trentonyo** [comment]
That’s weird, it’s not locating the package at all

**Comment by trentonyo** [comment]
> > For testing purposes, try installing from the test index with
> > ```
> > python -m pip install -i https://test.pypi.org/simple/ startout==0.2.2
> > ```
> 
> Is there any preliminary stuff I might have needed to do before running that command? As of now, this is what I see. I used macOS. 

Perhaps we can link up at some point and see why that's happening @HlaKarki

**Pull request merged**
